// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPcOelJcewcTcv8QIn7AKLkN5GKjla-V8',
    appId: '1:303823000990:web:6110898090d0cef198b28f',
    messagingSenderId: '303823000990',
    projectId: 'piranti-bergerak-a083d',
    authDomain: 'piranti-bergerak-a083d.firebaseapp.com',
    storageBucket: 'piranti-bergerak-a083d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVoSrWQajHn5PkpDeN8IfO6JqGsMNsyp0',
    appId: '1:303823000990:android:55267bd12c5426d098b28f',
    messagingSenderId: '303823000990',
    projectId: 'piranti-bergerak-a083d',
    storageBucket: 'piranti-bergerak-a083d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRQLvA5gIHxn4_9iMRY8ZmSW7gofO_7ng',
    appId: '1:303823000990:ios:7d2df1a8c1852bce98b28f',
    messagingSenderId: '303823000990',
    projectId: 'piranti-bergerak-a083d',
    storageBucket: 'piranti-bergerak-a083d.appspot.com',
    iosBundleId: 'com.example.pirantiBergerak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRQLvA5gIHxn4_9iMRY8ZmSW7gofO_7ng',
    appId: '1:303823000990:ios:9b79b7a713d36dbd98b28f',
    messagingSenderId: '303823000990',
    projectId: 'piranti-bergerak-a083d',
    storageBucket: 'piranti-bergerak-a083d.appspot.com',
    iosBundleId: 'com.example.pirantiBergerak.RunnerTests',
  );
}
